### ISSUE TITLE
搞到最后我发现还需要一个m-team的账号，pornhub难道不香吗

### ISSUE THREAD

**Issue by fejsfei** [JAVClub/core#10]

**Comment by LoliLin** [comment]
首先, 您的 PornHub 不能保证每个视频都有番号, 也不能保证视频的质量

其次, 如果不想使用 m-team 可以自行加入 OneJAV 的 driver 或者直接使用旧版 fetcher, 而不是在两个项目中简单粗暴地开无内容 IS

以上
