### ISSUE TITLE
你好, 请问可以更详细地描述一下实现原理吗?

### ISSUE THREAD

**Issue by Alpha2J** [JAVClub/core#13]
通过阅读文档, 可以知道该项目由三个子项目组成: fetcher, core, web, 
1. fetcher: 抓取种子 -> 推送qBittorrent下载 -> 处理 -> 上传Google Drive.
2. core: 读取 Google Drive 文件列表->导入本地数据库.
3. web: 展示信息.

针对上面三个部分, 我有如下的疑问点:
- 对于"1.":
  - "推送qBittorrent下载": "qBittorrent"是一个node的种子下载器lib吗? 还是说是第三方的种子下载服务呢?
- 对于"2.":
  - "导入本地数据库": 这里导入的是视频的内容吗? 但是Features上面不是说"视频、图片数据不占用本地空间"吗?

这些疑问我相信通过完成一遍项目的部署和阅读源码来得以解答, 但是在一些概念没有理解之前埋头去做这些事情性价比是不高的, 时间上会耗费更多. 因此想到来这里提一个issues向作者请教, 希望能得到回复. 非常感谢!

**Comment by LoliLin** [comment]
不想翻源码可以理解，不过最基本的搜索总是能做的吧，在这问 qBittorrent 是啥就感觉这 is 低了一个档次

导入数据库是指导入元数据，也就是封面链接、演员数据还有视频的 Google Drive 地址这些到本地数据库，视频本身并不在这个范围内

**Comment by isXiaoLin** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
