### ISSUE TITLE
希望能在core裡面直接實現抓取影片 (海外用戶)

### ISSUE THREAD

**Issue by yuanqiuye** [JAVClub/core#19]
本人只有一台Server，沒辦法再生一台Server做Worker QQ，而且本身在海外，也沒需求架一個proxy，不知道作者能不能實現我小小的願望w

**Comment by isXiaoLin** [comment]
core 与 fetcher 分两台机器只是推荐，实践过程中可以使用 Docker 将两个服务部署在同一台服务器上，参照 [JAVClub/docker](https://github.com/JAVClub/docker)

**Comment by yuanqiuye** [comment]
抱歉是我語義表達錯誤，是在module的Google Drive上面：
```
  async getFileURL (storageData) {
    if (this._data.encryption && this._data.encryption.secret && this._data.encryption.server) {
      const uri = cryptoJs.AES.encrypt(this._data.drive.driveId + '||!||' + storageData.fileId, this._data.encryption.secret).toString()
      const server = this._data.encryption.server.split(',')
      return server[randomInt(0, server.length - 1)] + '/' + base64.encode(uri)
    }
    return ''
  }
```
如果沒有配置proxy，core就不會回傳影片網址給dplayer QQ

**Comment by isXiaoLin** [comment]
如果说是 `config.json` 里面的那个 proxy, 留空即可, 那个是用来代理封面和 DMM 的截图的

数据库中 `driverData` 里面那个 proxy 是必须填写的, 因为要获取到云盘里的内容就必须要经过一层代理, 不然不管是从什么方面来讲都会有很多麻烦 (比如 CORS)

以及 proxy 并不需要使用自己的服务器, 可以使用 Vercel 和 Cloudflare 提供的免费服务, 如果只是个人使用的话完全够用了 (参照 [https://github.com/JAVClub/proxy](https://github.com/JAVClub/proxy)

不过你这情况有点小特殊可能得稍微改动一下程序才能使用, 可以稍微参考一下 [这里](https://github.com/JAVClub/proxy/blob/master/workers/app.js) 和 [这里](https://github.com/kulokenci/goindex-drive/blob/master/worker.js), 将后者获取 access key 部分代码移到前者即可 (当然如果实在不想改代码给个反馈我做点小修正即可

**Comment by yuanqiuye** [comment]
那就麻煩作者了，謝謝你！(ﾉ>ω<)ﾉ

**Comment by isXiaoLin** [comment]
在 https://github.com/JAVClub/proxy/commit/c22becc8d616bee3a4abdf9d31f16ea1fa9c221b 支持了, 临时糊出来的没做测试, 如果不能用可以给个反馈

以及如果使用这种方式, 频繁切换视频/拖动进度条**很可能**触发 ratelimit (即返回 403), 所以使用时得稍微注意一下
