### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by 9E307** [JAVClub/core#20]
使用过程中发现，出现封面图之后，鼠标点击图片不会跳转连接，而是需要点击文字才能跳转过去。所以希望能让图片也可以点击，扩大使用者的点击范围。因为直觉上都是直接对图片进行点击动作的。

另一个是关于播放页面的建议请考虑。希望播放页面能增加一些知名的第三方播放器的播放调用按钮，而不仅仅是在网页上播放。
还有如果可以的话建议爬虫程序能顺便爬取对应番号在DMM内的预告片。主要是觉得观看者在判断一部片子好不好看的时候除了DMM提供的预览图，预告视频也是很直接的一个参考。并且还能省下因为只是想快速预览十几秒的部分片段而对主视频调用的大量流量，也可以降低一下服务器负载。

**Comment by 9E307** [comment]
爬取DMM预告片指的是直接添加一个预告片的小窗口解析DMM的源视频地址，而不是让程序连预告片也下载到gdrive去存储。

**Comment by isXiaoLin** [comment]
前两个问题不大，有空会加上，但是第三个有点困难

现在我们熟知的番号都是 字母-三位数字，而DMM官网提供的番号复杂得多，还有多种格式，比如001XXX-000137目前还没有找到转换规则，所以...

**Comment by isXiaoLin** [comment]
Support in https://github.com/JAVClub/web/commit/f798b94e1ff665e165a8ba0e040b3426300fdf19

**Comment by 9E307** [comment]
javdb和jav321这两个网站的番号详情页提供了他们抓取的预览视频，那么是否可以考虑曲线救国一下，通过解析这俩网站的页面结构嵌套进去？

**Comment by isXiaoLin** [comment]
大概看了一下，javdb 的 URL 是随机生成的，所以说不可能直接访问到

实在有需要的话可以考虑前端新增 "在 javdb 中搜索" 选项

**Comment by isXiaoLin** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
