### ISSUE TITLE
卡在数据库那里

### ISSUE THREAD

**Issue by nalanshi** [JAVClub/core#21]
一直提示我
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''drivers' ('id','name','driverType','driverData','isEnable','createTime','update' at line 1
mysql的版本是5.5
操作就是手动建了一个名为drivers的表格，随后尝试添加记录失败

**Comment by isXiaoLin** [comment]
如果你是手动创建的 drivers 表，那说明你没好好看文档，请重新阅读文档

如果是自动创建的 drivers 表手动插入数据出错，请把插入使用的 SQL 语句抹除隐私后贴在这

**Comment by nalanshi** [comment]
> 如果你是手动创建的 drivers 表，那说明你没好好看文档，请重新阅读文档
> 
> 如果是自动创建的 drivers 表手动插入数据出错，请把插入使用的 SQL 语句抹除隐私后贴在这

嗯，重新阅读了一下，确实是我手动创建步骤有误，才发现大佬的创建模板，不过在创建videos表格时出现
CREATE TABLE `videos` (
    `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
    `metadataId` int(11) NOT NULL,
    `videoFileId` int(11) DEFAULT NULL,
    `isHiden` char(1) DEFAULT '0',
    `infoFileId` int(11) NOT NULL,
    `videoMetadata` json NOT NULL,
    `storyboardFileIdSet` json NOT NULL,
    `updateTime` tinytext NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL seT NULL,     `storyboardFileIdSet` json NOT NULL,     `updateTime` tinytex' at line 1


是不是因为我改成了utf8mb4_general_ci呢，主要是原本的哪个出错
ERROR 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci'

**Comment by isXiaoLin** [comment]
忘记说了, 数据库推荐使用 8.0+, 不然可能会出现各种问题

**Comment by nalanshi** [comment]
> 忘记说了, 数据库推荐使用 8.0+, 不然可能会出现各种问题

。。。。。。。，原来如此，我试试专门搭一个数据库服务器吧

**Comment by nalanshi** [comment]
不过8.0内存占用不少啊

**Comment by isXiaoLin** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
