### ISSUE TITLE
播放的时候会转码吗，服务器转码还是客户端转码？

### ISSUE THREAD

**Issue by ZhaoqiangCn** [JAVClub/core#22]

**Comment by isXiaoLin** [comment]
简单地说，不会，源文件怎么样发到客户端的就怎么样

**Comment by ZhaoqiangCn** [comment]
> 简单地说，不会，源文件怎么样发到客户端的就怎么样

所以说对服务器性能没什么要求对吧？

**Comment by isXiaoLin** [comment]
可以这样理解

**Comment by isXiaoLin** [comment]
This issue is closed due to not being active. Please feel free to open it again or create a new one and reference this if you have further questions.
