### ISSUE TITLE
构建web前端时一直报错

### ISSUE THREAD

**Issue by 0x959** [JAVClub/core#28]
root@instance-2:~/JAVClub_web# npm run build 构建web前端时一直报错，但是我尝试用 run dev 可以运行起来， 错误信息是：
⠏  Building for production...Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! web@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the web@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

我又尝试在全局安装了 vue-cli 还是无果， 原来在ubunbu 18下这样，更换 debian9也是一样。 core已经配置好能跑起来监听3000端口了，就差这个web，请大佬指路。 谢谢

**Comment by 0x959** [comment]
补充下： 是执行 npm run serve 可以正常启动

DONE  Compiled successfully in 9465ms                                                                             2:34:35 AM


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://10.170.0.10:8080/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

**Comment by isXiaoLin** [comment]
看了看[这里](https://github.com/vuejs/vue-cli/issues/2596)有一个相关 issue, 总结一下

方案一: 升级 Node/NPM
方案二: 清除 NPM 缓存(`npm cache clean --force`)+删除 `node_modules`+删除 `package-lock.json`

如果还是不行请附上构建时的 debug 日志

**Comment by 0x959** [comment]
npm: 6.14.7
node 14.7.0
还是不行， 之前我也使用过您说的方法，折腾2天啦，实在搞不定才过来问的。下面是debug.log

root@rssw:~/JAVClub_web# cat /root/.npm/_logs/2020-08-08T07_48_34_727Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v14.7.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v14.7.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v14.7.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle web@0.1.0~prebuild: web@0.1.0
6 info lifecycle web@0.1.0~build: web@0.1.0
7 verbose lifecycle web@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle web@0.1.0~build: PATH: /root/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/JAVClub_web/node_modules/.bin:/root/.nvm/versions/node/v14.7.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle web@0.1.0~build: CWD: /root/JAVClub_web
10 silly lifecycle web@0.1.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle web@0.1.0~build: Returned: code: 134  signal: null
12 info lifecycle web@0.1.0~build: Failed to exec build script
13 verbose stack Error: web@0.1.0 build: `vue-cli-service build`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v14.7.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid web@0.1.0
15 verbose cwd /root/JAVClub_web
16 verbose Linux 4.14.129-bbrplus
17 verbose argv "/root/.nvm/versions/node/v14.7.0/bin/node" "/root/.nvm/versions/node/v14.7.0/bin/npm" "run" "build"
18 verbose node v14.7.0
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 134
22 error web@0.1.0 build: `vue-cli-service build`
22 error Exit status 134
23 error Failed at the web@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Comment by isXiaoLin** [comment]
看起来一部分是玄学错误

本地构建了一份并发布到了 [JAVClub/web@v0.1.1](https://github.com/JAVClub/web/releases/tag/v0.1.1) 这里, 直接下载 web.zip 并解压到 `dist` 目录即可

**Comment by 0x959** [comment]
好的，可以了
