### ISSUE TITLE
請問展示站是不是不能用了

### ISSUE THREAD

**Issue by plok00286750** [JAVClub/core#34]
[https://i.imgur.com/qEWz29O.jpeg](url)
我打開就這樣子影片也不能播了

**Comment by isXiaoLin** [comment]
![image](https://user-images.githubusercontent.com/20554060/91634837-0f071280-ea26-11ea-8ca1-cabb9af468b7.png)
由于受到 CC 攻击，演示站使用的 Vercel 项目已被服务商暂停，在寻找到相关免费新服务前将无限期关停
