### ISSUE TITLE
有方法可以保存到本地嘛？

### ISSUE THREAD

**Issue by noname01pas** [JAVClub/core#4]
看 README 里面强调是资源本地不再占用，那么数据是在 IPFS 上的？本地可以另存为么？

**Comment by LoliLin** [comment]
并不是 IPFS, 是 Google Drive, 所有文件都可以在你上传到的 Google Drive 里找到

要下载到本地的话可以直接通过网页端下载或者 rclone

**Comment by noname01pas** [comment]
如果 Google Drive 的话，岂不是空间很有限？免费用户怎么办😰

看readme里面说`星际`，以为真的是 IPFS 呢。

**Comment by LoliLin** [comment]
星际在这个语境下其实是个形容词 (小声

免费用户的话可以考虑使用某些方面提供的免费 GSuite EDU 账户, 比如 https://www.huayuworld.org

**Comment by noname01pas** [comment]
这样受众可能有点小唉，是否可以考虑后端使用 S3 兼容的存储呢？例如

* AWS S3
* Aliyun OSS
* Azure Storage
* minio

**Comment by LoliLin** [comment]
理论来讲只要 rclone 支持的云端都是可以使用的, 程序也提供了接口帮助开发者将云端接入 JAVClub

详见 `src/import/driver/googleDrive.js` 及 `import/driver/googleDrive.js`

若有需求可以提交 PR

不过说实话相信这些厂商的 TOS 里都有明确说明不允许上传色情内容, 所以不管是哪里其实都应该算是滥用 (x

**Comment by noname01pas** [comment]
如果不是以此作为源，公开对外发布的话，厂商是不会在乎你 hosting 什么样子的内容的。

**Comment by LoliLin** [comment]
这么说也是, 不过现在个人所用的是 Google Drive, 因为相比其他厂商而言空间/价格比是最小的(毕竟无限容量), 如果有需要的话欢迎提交 PR

**Comment by gsons** [comment]
**我就看你们一本正经地讨论技术问题**

**Comment by SzHeJason** [comment]
我其实也写了一个本地爬取的脚本，其实并不复杂，不过作者也是厉害，一心为公，好人一生平安啊

**Comment by LoliLin** [comment]
JAVClub/web@997db4

已在视频列表中添加下载选项
