### ISSUE TITLE
Url Connection timed out

### ISSUE THREAD

**Issue by F7ionsy** [JAVClub/core#5]
Host error,公益站无法访问

**Comment by LoliLin** [comment]
可能是触发 Cloudflare 风控了, 可以挂代理访问

**Comment by F7ionsy** [comment]
更换了美国，台湾，日本节点均无法访问

**Comment by LoliLin** [comment]
测试了一下源站和 Cloudflare 应该都是没有问题的, 如果还需要不知道方不方便将 https://fuckloli.net/cdn-cgi/trace <https://fuckloli.net/cdn-cgi/trace> 截个图看下
