### ISSUE TITLE
测试站点报错

### ISSUE THREAD

**Issue by p354139076** [JAVClub/core#6]
The resource https://fuckloli.net/js/app.197df758.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
chrome下会报这个错，打开梯子或者关闭梯子都一样

**Comment by LoliLin** [comment]
添加 preload 是为了提高整体加载速度, 可能是你的国际互联网访问速度过慢或者某些资源被广告拦截插件拦截, 请在 Network 页勾选 disable cache 并重载后截图

**Comment by p354139076** [comment]
可以了，不用梯子的话会超时
