### ISSUE TITLE
Loading images may cause element layer to crash.

### ISSUE THREAD

**Issue by Co2333** [JAVClub/core#8]
[Offical Site]/#/metadata/list/61
[Offical Site]/#/metadata/view/357

![截屏2020-03-30 下午5 56 04](https://user-images.githubusercontent.com/25259084/77899982-f1cfeb80-72af-11ea-9ba4-3aa6349d1274.png)

https://proxy.____-img-2.w_____.___/https://pics.javbus.com/cover/7izv_b.jpg

**Comment by LoliLin** [comment]
成功复现

没有考虑到 cover 还有这种情况, 有空加个 max-height

(另外这是 WEB 的锅 (

**Comment by yyh84yangtao** [comment]
请问 nginx conf 是在哪里配置呢？

**Comment by LoliLin** [comment]
Fixed in https://github.com/JAVClub/web/commit/18b57fc5a33c42b455dceea640cafac20eebc6a1
